# Generated by Django 5.0.6 on 2024-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='JohnDoe', max_length=50)),
                ('userMail', models.EmailField(default='user@mail.com', max_length=254)),
                ('userPassword', models.CharField(max_length=20)),
                ('userAuthority', models.CharField(default='Member', max_length=15)),
            ],
        ),
    ]
