# Generated by Django 5.0.6 on 2024-07-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
